# Runtime-only overrides for Nextcloud: custom php.ini + optional local web bind.
# Runtime path (under RUNTIME_ROOT):
# - ${RUNTIME_ROOT}/stacks/nextcloud/php.ini (custom PHP settings)
# (RUNTIME_ROOT is required when using this override)
# Variables (from .env.example):
# - HTTP_PORT: host port for local web access (optional)
# - BIND_LOCALHOST: bind address for local-only access (optional)
# Security: keep ports on loopback and never commit secrets.

services:
  app:
    volumes:
      - ${RUNTIME_ROOT:?set RUNTIME_ROOT=/abs/path/to/homelab-runtime}/stacks/nextcloud/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro

  cron:
    volumes:
      - ${RUNTIME_ROOT:?set RUNTIME_ROOT=/abs/path/to/homelab-runtime}/stacks/nextcloud/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro

  web:
    # Optional local bind for the internal Nginx
    # ports:
    #   - "${BIND_LOCALHOST:-127.0.0.1}:${HTTP_PORT:-8082}:8080"

  mysqld-exporter:
    # Runtime-only credentials file for MariaDB exporter
    # Copy to ${RUNTIME_ROOT}/stacks/nextcloud/exporters/mysqld-exporter.my.cnf and edit.
    # (RUNTIME_ROOT is required when using this override)
    volumes:
      - ${RUNTIME_ROOT:?set RUNTIME_ROOT=/abs/path/to/homelab-runtime}/stacks/nextcloud/exporters/mysqld-exporter.my.cnf:/etc/mysqld-exporter/.my.cnf:ro
