# Runtime-only overrides for Cloudflared: config + credentials mounts.
# Runtime paths (under RUNTIME_ROOT):
# - ${RUNTIME_ROOT}/stacks/cloudflared/config.yaml (tunnel config)
# - ${RUNTIME_ROOT}/stacks/cloudflared/credentials.json (tunnel credentials)
# (RUNTIME_ROOT is required when using this override)
# Variables (from .env.example):
# - CLOUDFLARED_CRED_FILE: container path to credentials JSON
# Security: never commit credentials and avoid exposing ports.

services:
  cloudflared:
    volumes:
      - ${RUNTIME_ROOT:?set RUNTIME_ROOT=/abs/path/to/homelab-runtime}/stacks/cloudflared/config.yaml:/etc/cloudflared/config.yaml:ro
      - ${RUNTIME_ROOT:?set RUNTIME_ROOT=/abs/path/to/homelab-runtime}/stacks/cloudflared/credentials.json:${CLOUDFLARED_CRED_FILE}:ro
