# Runtime-only overrides for AdGuard Home: persistence + optional local binds.
# Runtime paths (under RUNTIME_ROOT):
# - ${RUNTIME_ROOT}/stacks/adguard-home/conf (AdGuardHome.yaml)
# - ${RUNTIME_ROOT}/stacks/adguard-home/work (runtime data)
# (RUNTIME_ROOT is required when using this override)
# Variables (from .env.example):
# - WEB_PORT: host port for the UI (optional)
# - DNS_PORT: host port for DNS (optional)
# Optional port bind (defaults inline):
# - BIND_LOCALHOST: bind address for local-only access (default: 127.0.0.1)
#   You may define these in your runtime .env if you want different values.
# Security: keep ports on loopback and never commit secrets.

services:
  adguard-home:
    volumes:
      - ${RUNTIME_ROOT:?set RUNTIME_ROOT=/abs/path/to/homelab-runtime}/stacks/adguard-home/conf:/opt/adguardhome/conf
      - ${RUNTIME_ROOT:?set RUNTIME_ROOT=/abs/path/to/homelab-runtime}/stacks/adguard-home/work:/opt/adguardhome/work
    # Optional local binds (recommended: loopback only)
    # ports:
    #   - "${BIND_LOCALHOST:-127.0.0.1}:${WEB_PORT:-3000}:3000"
    #   - "${BIND_LOCALHOST:-127.0.0.1}:${DNS_PORT:-53}:53/tcp"
    #   - "${BIND_LOCALHOST:-127.0.0.1}:${DNS_PORT:-53}:53/udp"
