name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint_and_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python for yamllint
        uses: actions/setup-python@v5

      - name: Install yamllint
        run: pip install yamllint

      - name: YAML lint
        run: yamllint stacks

      - name: Validate Docker Compose files (no pull, no up)
        run: |
          set -euo pipefail
          mapfile -t FILES < <(git ls-files "stacks/**/compose*.y*ml")
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No compose files found."
            exit 0
          fi
          for f in "${FILES[@]}"; do
            echo " - $f"
            docker compose -f "$f" config -q
          done
