# homelab-stacks/stacks/monitoring/compose.demo.logs.yaml
# -------------------------------------------------------------------
# Demo logs overlay
# - Adds Loki + Promtail and a simple "logspammer" to generate log lines
# - Uses demo volumes and the external "demo-net" network
# - Promtail binds are driven by .env.demo (rootful/rootless)
# -------------------------------------------------------------------

x-anchors:
  labels-demo: &labels_demo
    com.repo: homelab-stacks
    com.stack: monitoring
    com.env: demo
    com.logging: "true"
  restart-policy: &restart_policy unless-stopped
  networks:
    demo-only: &net_demo_only
      - demo-net

services:
  loki:
    image: grafana/loki@sha256:0eaee7bf39cc83aaef46914fb58f287d4f4c4be6ec96b86c2ed55719a75e49c8
    command: ["-config.file=/etc/loki/local-config.yaml"]
    expose:
      - "3100"
    volumes:
      - demo-loki-data:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3100/ready >/dev/null"]
      interval: 15s
      timeout: 3s
      retries: 6
    networks: *net_demo_only
    restart: *restart_policy
    labels: *labels_demo

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
    environment:
      - CONTAINERS=1
      - EVENTS=1
      - INFO=1
      - NETWORKS=1
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro${SELINUX_SUFFIX:-}
    networks: *net_demo_only
    restart: *restart_policy
    labels: *labels_demo

  promtail:
    image: grafana/promtail@sha256:086e4e85d2eb383fb04ea83c0f5074da81df56e415062ca888dba426abd8dfa5
    command:
      - -config.file=/etc/promtail/config.yaml
      - -config.expand-env=true
    expose:
      - "9080"
    volumes:
      - ./promtail/config.demo.yaml:/etc/promtail/config.yaml:ro
      - ${DOCKER_CONTAINERS_DIR:-/var/lib/docker/containers}:/var/lib/docker/containers:ro${SELINUX_SUFFIX:-}
      - demo-promtail-positions:/positions
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mon-demo}
      - DOCKER_HOST=${DOCKER_HOST:-tcp://docker-socket-proxy:2375}
    depends_on:
      - docker-socket-proxy
    healthcheck:
      test: ["CMD", "/usr/bin/promtail", "-version"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 15s
    networks: *net_demo_only
    restart: *restart_policy
    labels: *labels_demo

  # Generates 1 log line/sec to visualize in Loki quickly
  logspammer:
    image: busybox@sha256:355b3a1bf5609da364166913878a8508d4ba30572d02020a97028c75477e24ff
    command: ["sh", "-lc", "i=0; while :; do i=$$((i+1)); echo \"demo-log $$i $(date -Is)\"; sleep 1; done"]
    networks: *net_demo_only
    restart: *restart_policy
    labels: *labels_demo

networks:
  # demo-net: demo-only stack network
  demo-net: {}

volumes:
  demo-loki-data: {}
  demo-promtail-positions: {}
