# homelab-stacks/stacks/monitoring/compose.override.example.yaml
# -------------------------------------------------------------------
# Example runtime override for sensitive host mounts.
# Copy to ${RUNTIME_ROOT}/stacks/monitoring/compose.override.yml and edit.
# -------------------------------------------------------------------

services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
    environment:
      - CONTAINERS=1
      - EVENTS=1
      - INFO=1
      - NETWORKS=1
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro${SELINUX_SUFFIX}
    networks:
      - mon-net
    restart: unless-stopped

  prometheus:
    volumes:
      # Runtime-only blackbox targets (file_sd_configs)
      # Copy to ${RUNTIME_ROOT}/stacks/monitoring/compose.override.yml and edit.
      # (RUNTIME_ROOT is required when using this override)
      - ${RUNTIME_ROOT:?set RUNTIME_ROOT=/abs/path/to/homelab-runtime}/stacks/monitoring/prometheus/targets:/etc/prometheus/targets:ro${SELINUX_SUFFIX}

  promtail:
    environment:
      DOCKER_HOST: ${DOCKER_HOST}
    volumes:
      - ${DOCKER_CONTAINERS_DIR}:/var/lib/docker/containers:ro${SELINUX_SUFFIX}

  alertmanager:
    volumes:
      # Example secret mount (bot_token_file in alertmanager.yml)
      - /srv/secrets/alertmanager/TG_BOT_TOKEN:/run/secrets/telegram_bot_token:ro
    # Runtime-only external URL for Alert/Silence links in Telegram.
    # Note: overriding command replaces the full list, so keep --config.file.
    # command:
    #   - "--config.file=/etc/alertmanager/alertmanager.yml"
    #   - "--web.external-url=https://alertmanager.<your-domain>"

  node-exporter:
    volumes:
      - ${HOST_ROOT:-/}:/host:ro,rslave${SELINUX_SUFFIX}
      - ${BACKUP_TEXTFILE_DIR:-/var/lib/node_exporter/textfile_collector}:/textfile-collector:ro${SELINUX_SUFFIX}

  cadvisor:
    volumes:
      - ${HOST_ROOT:-/}:/rootfs:ro${SELINUX_SUFFIX}
      - ${HOST_VAR_RUN:-/var/run}:/var/run:ro${SELINUX_SUFFIX}
      - ${HOST_SYS:-/sys}:/sys:ro${SELINUX_SUFFIX}
      - ${HOST_DOCKER_DIR:-/var/lib/docker}:/var/lib/docker:ro${SELINUX_SUFFIX}
